// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/cheng/message/prototest2/Data2.proto

package com.cheng.message.prototest2;

public final class Data2Pro {
  private Data2Pro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Data2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 status = 1;
    boolean hasStatus();
    int getStatus();
    
    // optional int32 cmd = 2;
    boolean hasCmd();
    int getCmd();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional .proto.Data data = 4;
    boolean hasData();
    com.cheng.message.prototest.DataPro.Data getData();
    com.cheng.message.prototest.DataPro.DataOrBuilder getDataOrBuilder();
  }
  public static final class Data2 extends
      com.google.protobuf.GeneratedMessage
      implements Data2OrBuilder {
    // Use Data2.newBuilder() to construct.
    private Data2(Builder builder) {
      super(builder);
    }
    private Data2(boolean noInit) {}
    
    private static final Data2 defaultInstance;
    public static Data2 getDefaultInstance() {
      return defaultInstance;
    }
    
    public Data2 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cheng.message.prototest2.Data2Pro.internal_static_proto_Data2_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cheng.message.prototest2.Data2Pro.internal_static_proto_Data2_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional int32 cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCmd() {
      return cmd_;
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .proto.Data data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.cheng.message.prototest.DataPro.Data data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.cheng.message.prototest.DataPro.Data getData() {
      return data_;
    }
    public com.cheng.message.prototest.DataPro.DataOrBuilder getDataOrBuilder() {
      return data_;
    }
    
    private void initFields() {
      status_ = 0;
      cmd_ = 0;
      name_ = "";
      data_ = com.cheng.message.prototest.DataPro.Data.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cheng.message.prototest2.Data2Pro.Data2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cheng.message.prototest2.Data2Pro.Data2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cheng.message.prototest2.Data2Pro.Data2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cheng.message.prototest2.Data2Pro.internal_static_proto_Data2_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cheng.message.prototest2.Data2Pro.internal_static_proto_Data2_fieldAccessorTable;
      }
      
      // Construct using com.cheng.message.prototest2.Data2Pro.Data2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (dataBuilder_ == null) {
          data_ = com.cheng.message.prototest.DataPro.Data.getDefaultInstance();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cheng.message.prototest2.Data2Pro.Data2.getDescriptor();
      }
      
      public com.cheng.message.prototest2.Data2Pro.Data2 getDefaultInstanceForType() {
        return com.cheng.message.prototest2.Data2Pro.Data2.getDefaultInstance();
      }
      
      public com.cheng.message.prototest2.Data2Pro.Data2 build() {
        com.cheng.message.prototest2.Data2Pro.Data2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cheng.message.prototest2.Data2Pro.Data2 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cheng.message.prototest2.Data2Pro.Data2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cheng.message.prototest2.Data2Pro.Data2 buildPartial() {
        com.cheng.message.prototest2.Data2Pro.Data2 result = new com.cheng.message.prototest2.Data2Pro.Data2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cheng.message.prototest2.Data2Pro.Data2) {
          return mergeFrom((com.cheng.message.prototest2.Data2Pro.Data2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cheng.message.prototest2.Data2Pro.Data2 other) {
        if (other == com.cheng.message.prototest2.Data2Pro.Data2.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              com.cheng.message.prototest.DataPro.Data.Builder subBuilder = com.cheng.message.prototest.DataPro.Data.newBuilder();
              if (hasData()) {
                subBuilder.mergeFrom(getData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 status = 1;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 cmd = 2;
      private int cmd_ ;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCmd() {
        return cmd_;
      }
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional .proto.Data data = 4;
      private com.cheng.message.prototest.DataPro.Data data_ = com.cheng.message.prototest.DataPro.Data.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cheng.message.prototest.DataPro.Data, com.cheng.message.prototest.DataPro.Data.Builder, com.cheng.message.prototest.DataPro.DataOrBuilder> dataBuilder_;
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.cheng.message.prototest.DataPro.Data getData() {
        if (dataBuilder_ == null) {
          return data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      public Builder setData(com.cheng.message.prototest.DataPro.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setData(
          com.cheng.message.prototest.DataPro.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeData(com.cheng.message.prototest.DataPro.Data value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              data_ != com.cheng.message.prototest.DataPro.Data.getDefaultInstance()) {
            data_ =
              com.cheng.message.prototest.DataPro.Data.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = com.cheng.message.prototest.DataPro.Data.getDefaultInstance();
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.cheng.message.prototest.DataPro.Data.Builder getDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      public com.cheng.message.prototest.DataPro.DataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cheng.message.prototest.DataPro.Data, com.cheng.message.prototest.DataPro.Data.Builder, com.cheng.message.prototest.DataPro.DataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cheng.message.prototest.DataPro.Data, com.cheng.message.prototest.DataPro.Data.Builder, com.cheng.message.prototest.DataPro.DataOrBuilder>(
                  data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.Data2)
    }
    
    static {
      defaultInstance = new Data2(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.Data2)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Data2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Data2_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/cheng/message/prototest2/Data2.pro" +
      "to\022\005proto\032&com/cheng/message/prototest/D" +
      "ata.proto\"M\n\005Data2\022\016\n\006status\030\001 \001(\005\022\013\n\003cm" +
      "d\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\031\n\004data\030\004 \001(\0132\013.pr" +
      "oto.DataB(\n\034com.cheng.message.prototest2" +
      "B\010Data2Pro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_Data2_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_Data2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Data2_descriptor,
              new java.lang.String[] { "Status", "Cmd", "Name", "Data", },
              com.cheng.message.prototest2.Data2Pro.Data2.class,
              com.cheng.message.prototest2.Data2Pro.Data2.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cheng.message.prototest.DataPro.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
