package com.cheng.mybatis.test.model;

public class ConfigAge extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_age.id
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_age.age
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_age.id
     *
     * @return the value of config_age.id
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_age.id
     *
     * @param id the value for config_age.id
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_age.age
     *
     * @return the value of config_age.age
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_age.age
     *
     * @param age the value for config_age.age
     *
     * @mbg.generated Sat Mar 03 00:24:22 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}