package com.cheng.mybatis.test.model;

public class ConfigUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_user.id
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_user.name
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_user.id
     *
     * @return the value of config_user.id
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_user.id
     *
     * @param id the value for config_user.id
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_user.name
     *
     * @return the value of config_user.name
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_user.name
     *
     * @param name the value for config_user.name
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}