package com.cheng.mybatis.test.mappers;

import com.cheng.mybatis.test.model.ConfigUser;
import com.cheng.mybatis.test.model.ConfigUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    long countByExample(ConfigUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int deleteByExample(ConfigUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int insert(ConfigUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int insertSelective(ConfigUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    List<ConfigUser> selectByExample(ConfigUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    ConfigUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ConfigUser record, @Param("example") ConfigUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int updateByExample(@Param("record") ConfigUser record, @Param("example") ConfigUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int updateByPrimaryKeySelective(ConfigUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_user
     *
     * @mbg.generated Sat Mar 03 00:50:21 CST 2018
     */
    int updateByPrimaryKey(ConfigUser record);
}